# Generated by Django 2.1.7 on 2019-03-01 13:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='APIRateLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('requests', models.IntegerField(verbose_name=0)),
                ('window_start', models.IntegerField(verbose_name=0)),
            ],
        ),
        migrations.CreateModel(
            name='AURAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AURUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uid', models.IntegerField(default=1)),
                ('realname', models.CharField(default='', max_length=255)),
                ('suspended', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=False)),
                ('reset_key', models.CharField(default='', max_length=32)),
                ('lang_preference', models.CharField(default='en', max_length=6)),
                ('tz', models.CharField(default='UTC', max_length=32)),
                ('homepage', models.TextField(blank=True, default='', null=True)),
                ('irc_nick', models.CharField(default='', max_length=32)),
                ('pgp_key', models.CharField(blank=True, max_length=40, null=True)),
                ('last_login_ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('last_ssh_login', models.DateTimeField(blank=True, null=True)),
                ('last_ssh_login_ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('inactivity_ts', models.IntegerField(default=0)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('comment_notify', models.BooleanField(default=True)),
                ('update_notify', models.BooleanField(default=False)),
                ('ownership_notify', models.BooleanField(default=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.AURAccountType')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('ip_address', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('banned_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SSHPubKey',
            fields=[
                ('fingerprint', models.CharField(max_length=44, primary_key=True, serialize=False)),
                ('pub_key', models.CharField(max_length=4096)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to='users.AURUser')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=8000)),
                ('revision', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='acceptedterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted', to='users.Term'),
        ),
        migrations.AddField(
            model_name='acceptedterm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_terms', to='users.AURUser'),
        ),
    ]
