# Generated by Django 2.1.7 on 2019-02-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='APIRateLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('requests', models.IntegerField(verbose_name=0)),
                ('window_start', models.IntegerField(verbose_name=0)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=8000)),
                ('revision', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='auruser',
            name='realname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='acceptedterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted', to='users.Term'),
        ),
        migrations.AddField(
            model_name='acceptedterm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_terms', to='users.AURUser'),
        ),
    ]
