# Generated by Django 2.1.7 on 2019-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190221_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auruser',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
