# Generated by Django 2.1.7 on 2019-02-21 11:09

from django.db import migrations
import django.utils.timezone
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190221_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auruser',
            name='last_ssh_login',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auruser',
            name='registered_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ban',
            name='ban_timestamp',
            field=django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now),
        ),
    ]
