# Generated by Django 2.1.7 on 2019-02-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190221_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='id',
        ),
        migrations.AlterField(
            model_name='ban',
            name='ip_address',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
