# Generated by Django 2.1.7 on 2019-02-22 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190222_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='ban_timestamp',
        ),
        migrations.AddField(
            model_name='ban',
            name='banned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
