# Generated by Django 2.1.7 on 2019-02-20 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PackageBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('popularity', models.FloatField(default=0.0)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('out_of_date_at', models.DateTimeField(blank=True, null=True)),
                ('flagger_comment', models.CharField(default='', max_length=255)),
                ('flagger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flagged', to=settings.AUTH_USER_MODEL)),
                ('maintainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintained', to=settings.AUTH_USER_MODEL)),
                ('packager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='packaged', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PackageComaintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('package_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comaintainers', to='packages.PackageBase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comaintained', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rendered_comment', models.TextField()),
                ('commented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_comments', to=settings.AUTH_USER_MODEL)),
                ('edited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edited_comments', to=settings.AUTH_USER_MODEL)),
                ('package_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='packages.PackageBase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(default='', max_length=255)),
                ('condition', models.CharField(default='', max_length=255)),
                ('arch', models.CharField(blank=True, max_length=255, null=True)),
                ('dep_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='package_deps', to='packages.DependencyType')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deps', to='packages.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_groups', to='packages.Group')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_groups', to='packages.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('package_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='packages.PackageBase')),
            ],
        ),
        migrations.CreateModel(
            name='PackageLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='package_licenses', to='packages.License')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_license', to='packages.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='packages.PackageBase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('arch', models.CharField(blank=True, max_length=255, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='packages.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('merged_name', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('closure_comment', models.TextField()),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=0)),
                ('package_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='packages.PackageBase')),
            ],
        ),
        migrations.CreateModel(
            name='PackageSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='/dev/null', max_length=8000)),
                ('arch', models.CharField(blank=True, max_length=255, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='packages.Package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('package_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='packages.PackageBase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SSHPubKey',
            fields=[
                ('fingerprint', models.CharField(max_length=44, primary_key=True, serialize=False)),
                ('pub_key', models.CharField(max_length=4096)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='req_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_requests', to='packages.RequestType'),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagerelation',
            name='rel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_relations', to='packages.RelationType'),
        ),
        migrations.AddField(
            model_name='package',
            name='package_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.PackageBase'),
        ),
    ]
