# Generated by Django 2.1.7 on 2019-02-20 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebase',
            name='flagger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flagged', to='users.AURUser'),
        ),
        migrations.AlterField(
            model_name='packagebase',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintained', to='users.AURUser'),
        ),
        migrations.AlterField(
            model_name='packagebase',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='packagebase',
            name='packager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='packaged', to='users.AURUser'),
        ),
        migrations.AlterField(
            model_name='packagebase',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submitted', to='users.AURUser'),
        ),
        migrations.AlterField(
            model_name='packagecomaintainer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comaintained', to='users.AURUser'),
        ),
        migrations.AlterField(
            model_name='packagecomments',
            name='deleted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_comments', to='users.AURUser'),
        ),
        migrations.AlterField(
            model_name='packagecomments',
            name='edited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edited_comments', to='users.AURUser'),
        ),
        migrations.AlterField(
            model_name='packagecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.AURUser'),
        ),
        migrations.AlterField(
            model_name='packagenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_notifications', to='users.AURUser'),
        ),
        migrations.AlterField(
            model_name='packagerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_requests', to='users.AURUser'),
        ),
        migrations.AlterField(
            model_name='packagevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='users.AURUser'),
        ),
        migrations.AlterField(
            model_name='sshpubkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to='users.AURUser'),
        ),
    ]
