# Generated by Django 2.1.7 on 2019-03-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuvoteinfo',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tu_voteinfos', to='users.AURUser'),
        ),
        migrations.AddField(
            model_name='tuvote',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tu_votes', to='packages.TUVoteInfo'),
        ),
        migrations.AddField(
            model_name='tuvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tu_votes', to='users.AURUser'),
        ),
        migrations.AddField(
            model_name='packagevote',
            name='package_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='packages.PackageBase'),
        ),
        migrations.AddField(
            model_name='packagevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='users.AURUser'),
        ),
        migrations.AddField(
            model_name='packagesource',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='package_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='packages.PackageBase'),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='req_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_requests', to='packages.RequestType'),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_requests', to='users.AURUser'),
        ),
        migrations.AddField(
            model_name='packagerelation',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packagerelation',
            name='rel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_relations', to='packages.RelationType'),
        ),
        migrations.AddField(
            model_name='packagenotification',
            name='package_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='packages.PackageBase'),
        ),
        migrations.AddField(
            model_name='packagenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_notifications', to='users.AURUser'),
        ),
        migrations.AddField(
            model_name='packagelicense',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='package_licenses', to='packages.License'),
        ),
        migrations.AddField(
            model_name='packagelicense',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_license', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packagekeyword',
            name='package_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='packages.PackageBase'),
        ),
        migrations.AddField(
            model_name='packagegroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_groups', to='packages.Group'),
        ),
        migrations.AddField(
            model_name='packagegroup',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_groups', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packagedependency',
            name='dep_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='package_deps', to='packages.DependencyType'),
        ),
        migrations.AddField(
            model_name='packagedependency',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deps', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='packagecomments',
            name='deleted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_comments', to='users.AURUser'),
        ),
        migrations.AddField(
            model_name='packagecomments',
            name='edited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edited_comments', to='users.AURUser'),
        ),
        migrations.AddField(
            model_name='packagecomments',
            name='package_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='packages.PackageBase'),
        ),
        migrations.AddField(
            model_name='packagecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.AURUser'),
        ),
        migrations.AddField(
            model_name='packagecomaintainer',
            name='package_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comaintainers', to='packages.PackageBase'),
        ),
        migrations.AddField(
            model_name='packagecomaintainer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comaintained', to='users.AURUser'),
        ),
        migrations.AddField(
            model_name='packagebase',
            name='flagger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flagged', to='users.AURUser'),
        ),
        migrations.AddField(
            model_name='packagebase',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintained', to='users.AURUser'),
        ),
        migrations.AddField(
            model_name='packagebase',
            name='packager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pkgbases', to='users.AURUser'),
        ),
        migrations.AddField(
            model_name='packagebase',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submitted', to='users.AURUser'),
        ),
        migrations.AddField(
            model_name='package',
            name='package_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packages.PackageBase'),
        ),
        migrations.AddField(
            model_name='officialprovider',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_providers', to='packages.Package'),
        ),
    ]
