# Generated by Django 2.1.7 on 2019-02-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('packages', '0002_auto_20190220_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(max_length=64)),
                ('provides', models.CharField(max_length=64)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_providers', to='packages.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=8000)),
                ('revision', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TUVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TUVoteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.TextField()),
                ('user', models.CharField(max_length=32)),
                ('submitted_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('yes', models.IntegerField(default=0)),
                ('no', models.IntegerField(default=0)),
                ('abstrain', models.IntegerField(default=0)),
                ('active_tus', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tuvote',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tu_votes', to='packages.TUVoteInfo'),
        ),
        migrations.AddField(
            model_name='tuvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tu_votes', to='users.AURUser'),
        ),
    ]
