# Generated by Django 2.1.7 on 2019-02-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20190221_0719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Term',
        ),
    ]
